.TH SOAPUI 1 "April 17, 2016" "version 5.2.1"
.SH NAME
soapui \- SoapUI Open Source
.SH SYNOPSIS
.B soapui
.SH DESCRIPTION

\fBSoapUI\fP Is a free and open source cross-platform
functional testing solution for APIs and web services.

.SH SEE ALSO
For more information on the usage of the program visit
http://www.soapui.org

This manual page was written by Yadickson Soto <yadickson@gmail.com>,
for the Debian GNU/Linux system (but may be used by others).
